### ISSUE TITLE
INDIAN MOBILE VERIFICATION CODES NOT RECEIVING

### ISSUE THREAD

**Issue by intutkri2** [Cryptonomica/cryptonomica#11]
My Cryptonomica registered email is tulasi.krishna92@gmail.com. I am not recieving mobile verification codes on Indian mobile numbers Please resolve

**Comment by ageyev** [comment]
RESOLVED

**Comment by ls4825783** [comment]
My registered email is ls4825783@gmail.com , I have submitted wrong id proof by mistake, how can I change that and I am not getting sms for verify the account?
