### ISSUE TITLE
Verification process

### ISSUE THREAD

**Issue by tamergamal** [Cryptonomica/cryptonomica#15]
I tried to upload video verification but web page didn't respond although i have good internet connection

Kindly advice
cryptonomica.net

**Comment by ageyev** [comment]
In general: try to reload the page. 
Use Chrome, Firefox or Opera only.

**Comment by tamergamal** [comment]
Already did many times reloading use chrome but also no respond

Sent from my iPhone

On Oct 3, 2018, at 12:52 PM, Viktor Ageyev <notifications@github.com<mailto:notifications@github.com>> wrote:


In general: try to reload the page.
Use Chrome, Firefox or Opera only.
