### ISSUE TITLE
Video server 

### ISSUE THREAD

**Issue by cryptoalchemi** [Cryptonomica/cryptonomica#18]
Hi Video records but crashes when trying to upload? Can this be fixed need verification as quickly as possible. Thanks

**Comment by ageyev** [comment]
What is the size of your video? 
What is the resolution of the video? 
What browser and OS do you use? 
What is your Internet connection?

**Comment by cryptoalchemi** [comment]
It's from the verify key screen to captures through there so the resolution is set. 

60MB
Chrome / Apple
90 Down / 11 Up  *Mbps

**Comment by ageyev** [comment]
You can: 
1) try another Browser/OS, for example use mobile device to record and upload video (just login with the same google account) or Opera/Firefox on macOS
2) send your video to support@cryptonomica.net , please also indicate the key fingerprint in your email

**Comment by cryptoalchemi** [comment]
Thanks
1. Worked after using firefox browser and upgrading flash player.  Do you know a rough eta for how long it takes to get verified?  

Thank you!

**Comment by ageyev** [comment]
Usually it takes up to 24 hours
