### ISSUE TITLE
Name does not match documents provided

### ISSUE THREAD

**Issue by AJ5629** [Cryptonomica/cryptonomica#19]

**Comment by ageyev** [comment]
Can you explain, please?

**Comment by AJ5629** [comment]
I have a first name, no middle name, last name, and a suffix. There is no way to add a suffix as prompted. How do I resolve this issue?

**Comment by AJ5629** [comment]
My full legal name is as follows: Arthur Feggins Jr.
First Name: Arthur
Last Name: Feggins
Suffix: Jr.
My passport shows as : Surname: Feggins Jr.

                                                : Given name: Arthur

 

Thanks and Regards,

Art Feggins

Sr. Teradata Consultant

Home: +1 323 200 2150 || Thai Mobile: +66 92 347 2109 (GMT+7)

You could have everything, but where would you put it?

I do not send or receive attachments, use DropBox or Google Drive!!!

 

On 1/10/19, 23:47, "Viktor Ageyev" <notifications@github.com> wrote:

 

Can you explain, please?

**Comment by ageyev** [comment]
We (Cryptonomica.net) do not require to enter the suffix. First and last name are enough.

**Comment by AJ5629** [comment]
I understand, however an error was flagged when I returned to STEX to complete the verification process after uploading my passport and driver license.

**Comment by ageyev** [comment]
"an error was flagged when I returned to STEX to complete the verification process"
--- this is because you did not finished verification on the cryptonomica.net 
Please, see my email message.
