### ISSUE TITLE
TwilioRestException error on phone number step of verification

### ISSUE THREAD

**Issue by shotcollin** [Cryptonomica/cryptonomica#24]
I'm in the process of online verification and after entering my (US) phone phone number and clicking `Send SMS Message` I get the error `com.twilio.sdk.TwilioRestException: Authenticate`. 

I believe the phone number is in the correct international format because when trying to format differently I received errors such as `Error type: INVALID_COUNTRY_CODE. Could not interpret numbers after plus-sign.` I have tried this step with Brave Browser (ver 1.18.78 Chromium 87.0.4280.141) and Safari (13.1.3) on macOS (10.15.7), as well as with Firefox (78.6.1esr) on Debian 10. The error is the same on each.

**Comment by shotcollin** [comment]
The problem persists.

**Comment by ageyev** [comment]
Do you use a real mobile phone or virtual number? 
Can you mail your phone number and PGP fingerprint to support@cryptonomica.net?

**Comment by shotcollin** [comment]
Just sent the info via email.
    
    On 1/17/21 8:12 AM, Viktor Ageyev
      wrote:
    
    
      
      Do you use a real mobile phone or virtual number?
        Can you mail your phone number and PGP fingerprint to support@cryptonomica.net?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Cryptonomica/cryptonomica/issues/24#issuecomment-761828054",
"url": "https://github.com/Cryptonomica/cryptonomica/issues/24#issuecomment-761828054",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
