### ISSUE TITLE
online verification error code creditcard

### ISSUE THREAD

**Issue by elmer151290** [Cryptonomica/cryptonomica#25]
hello,

i payed wih my creditcard and in the next step it asks for the 7 digit code that stands in the description.
when i enter the digit code i get a error code:

Error:
java.lang.Exception: Code does not much. It was attempt # 1

i tried multiple ways with capitals or not, numbers at the front or back. 
everytime the same error code.
what am i doing wrong?

**Comment by ogi24** [comment]
Hi. I cannot make the registration and I want this not more.
But I pay to you 31.68 EUR on 2021/01/11.
Please return me this amount.
Regards

**Comment by ageyev** [comment]
@ogi24 your payment was refunded, and the profile on Cryptonomica was deleted. 
Refunds usually take 5-10 business days.
