### ISSUE TITLE
Verification: Problem with uploading to server

### ISSUE THREAD

**Issue by irasmaster** [Cryptonomica/cryptonomica#27]
I am not able to upload to server the verification video. I noticed an error in Console every time I hit "upload to server" button.
![cryptonomica-upload-error](https://user-images.githubusercontent.com/4116106/145575089-d2b0c6f5-a002-4857-a14b-c6150a009bb6.png)

**Comment by ageyev** [comment]
Thank you for reporting. 
Please try again, should work now.
