### ISSUE TITLE
Cannot register on www.cryptonomica.work

### ISSUE THREAD

**Issue by Renaud-V** [Cryptonomica/cryptonomica#4]
When trying to register on www.cryptonomica.work we get "Authorization required".

Same error on www.cryptonomica.net

**Comment by ageyev** [comment]
You have to login with google account. 
See https://youtu.be/5n9OP1smGHM?t=1m12s

**Comment by ageyev** [comment]
When you click "Register" you should see a pop-up window from Google with a form to sign in and  to grant permission for Cryptonomica to authenticate you with your Google account.

**Comment by Renaud-V** [comment]
I did log with google account.
![image](https://cloud.githubusercontent.com/assets/5773192/16006465/951f75c2-316d-11e6-9b9a-3bae6124d49f.png)

**Comment by ageyev** [comment]
Thank you for screen-shot. 
Is your browser's cookie functionality turned off? 
Can you, please, to try with another browser? 

contact me on http://slack.cryptonomica.net

**Comment by Renaud-V** [comment]
Indeed the browser needs to accept third party cookies.
On the register form, the field "Information about you" is not optional, if left empty you get a "_**java.lang.Exception: Info can not be empty**_" error. Once filled, no problem.

**Comment by ageyev** [comment]
Now, I made "Information about you" in registration form optional. 
Commit: cb15e82ef2e08c1700f561157184b6cd62465672
