### ISSUE TITLE
A misprint on the main page

### ISSUE THREAD

**Issue by iljenochka** [Cryptonomica/cryptonomica#8]
A misprint on the main page:

"Using verified user's public key you can:

Verify his/her signature on contract or another legally binding documents. Signature done with verified key is considered as user's own signature on document in arbitration tribunal under IACC Arbitration Rules, and thus such contract, agreement or obligation will be legally (yes, we are not only hackers, but lawyers, trust us ...) recognizable and enforceable in all counties - parties of The New York Convention 1958 (currently 156)"

![2016-11-30_0442](https://cloud.githubusercontent.com/assets/24198893/20737795/bcb6cfde-b6b7-11e6-894d-cd56c1d5ff2d.png)

**Comment by ageyev** [comment]
Landing page is changed: [cryptonomica.net](https://cryptonomica.net/)
